Started GET "/" for 172.31.0.1 at 2020-08-08 06:34:32 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:34:32 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  [1m[35m (124.6ms)[0m  [1m[35mCREATE DATABASE "savvy-api-rails_development" ENCODING = 'utf8'[0m
  [1m[35m (111.9ms)[0m  [1m[35mCREATE DATABASE "savvy-api-rails_test" ENCODING = 'utf8'[0m
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:17 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:17 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:20 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:20 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:20 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:21 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:21 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:21 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:33 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:33 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:34 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:34 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:34 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:35 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:36:35 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:36:35 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "app_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 06:37:15 +0000
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/templates/rails/welcome/index.html.erb (Duration: 9.2ms | Allocations: 295)
Completed 200 OK in 14ms (Views: 11.9ms | ActiveRecord: 0.0ms | Allocations: 1538)


Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 06:37:15 +0000
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/" for 172.31.0.1 at 2020-08-08 10:35:31 +0000
Processing by Rails::WelcomeController#index as HTML
  Rendering /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/templates/rails/welcome/index.html.erb
  Rendered /usr/local/bundle/gems/railties-6.0.3.2/lib/rails/templates/rails/welcome/index.html.erb (Duration: 13.5ms | Allocations: 295)
Completed 200 OK in 31ms (Views: 18.3ms | ActiveRecord: 0.0ms | Allocations: 1692)


Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-08 10:35:32 +0000
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1" for 172.31.0.1 at 2020-08-08 10:35:43 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/user" for 172.31.0.1 at 2020-08-08 10:35:53 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1/user"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:35:58 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/users" for 172.31.0.1 at 2020-08-08 10:36:18 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/users" for 172.31.0.1 at 2020-08-08 10:36:52 +0000
  
NameError (uninitialized constant V1::Root::Users):
  
app/api/v1/root.rb:3:in `<class:Root>'
app/api/v1/root.rb:1:in `<main>'
app/api/api_base.rb:2:in `<class:ApiBase>'
app/api/api_base.rb:1:in `<main>'
config/routes.rb:2:in `block in <main>'
config/routes.rb:1:in `<main>'
Started GET "/api/users" for 172.31.0.1 at 2020-08-08 10:37:19 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:37:26 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api" for 172.31.0.1 at 2020-08-08 10:38:11 +0000
  
ActionController::RoutingError (No route matches [GET] "/api"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/" for 172.31.0.1 at 2020-08-08 10:38:17 +0000
  
ActionController::RoutingError (No route matches [GET] "/api"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/" for 172.31.0.1 at 2020-08-08 10:41:05 +0000
Started GET "/api/" for 172.31.0.1 at 2020-08-08 10:44:13 +0000
Started GET "/api/user" for 172.31.0.1 at 2020-08-08 10:44:26 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/user"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/users" for 172.31.0.1 at 2020-08-08 10:44:31 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api" for 172.31.0.1 at 2020-08-08 10:44:41 +0000
Started GET "/api" for 172.31.0.1 at 2020-08-08 10:46:09 +0000
  
NameError (uninitialized constant V1::Root::Users):
  
app/api/v1/root.rb:5:in `<class:Root>'
app/api/v1/root.rb:1:in `<main>'
app/api/api_base.rb:4:in `<class:ApiBase>'
app/api/api_base.rb:1:in `<main>'
config/routes.rb:2:in `block in <main>'
config/routes.rb:1:in `<main>'
Started GET "/api" for 172.31.0.1 at 2020-08-08 10:46:36 +0000
  
ActionController::RoutingError (No route matches [GET] "/api"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api" for 172.31.0.1 at 2020-08-08 10:46:37 +0000
  
ActionController::RoutingError (No route matches [GET] "/api"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api" for 172.31.0.1 at 2020-08-08 10:46:37 +0000
  
ActionController::RoutingError (No route matches [GET] "/api"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1" for 172.31.0.1 at 2020-08-08 10:46:46 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:47:00 +0000
  
NameError (uninitialized constant V1::Root::Users):
  
app/api/v1/root.rb:5:in `<class:Root>'
app/api/v1/root.rb:1:in `<main>'
app/api/api_base.rb:4:in `<class:ApiBase>'
app/api/api_base.rb:1:in `<main>'
config/routes.rb:2:in `block in <main>'
config/routes.rb:1:in `<main>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:47:12 +0000
  
NameError (uninitialized constant V1::Root::Users):
  
app/api/v1/root.rb:5:in `<class:Root>'
app/api/v1/root.rb:1:in `<main>'
app/api/api_base.rb:4:in `<class:ApiBase>'
app/api/api_base.rb:1:in `<main>'
config/routes.rb:2:in `block in <main>'
config/routes.rb:1:in `<main>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:47:27 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:49:49 +0000
  
NameError (uninitialized constant V1::Root::Users):
  
app/api/v1/root.rb:6:in `<class:Root>'
app/api/v1/root.rb:1:in `<main>'
app/api/api_base.rb:4:in `<class:ApiBase>'
app/api/api_base.rb:1:in `<main>'
config/routes.rb:2:in `block in <main>'
config/routes.rb:1:in `<main>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:55:00 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:57:14 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:57:15 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:57:15 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:57:15 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:57:42 +0000
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/services/user_service/get_info.rb:2:in `call'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:58:14 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:58:15 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:58:16 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:58:16 +0000
  
ArgumentError (wrong number of arguments (given 1, expected 0)):
  
app/services/application_service.rb:8:in `initialize'
app/services/application_service.rb:8:in `new'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:58:36 +0000
  
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/services/user_service/get_info.rb:2:in `call'
app/services/application_service.rb:8:in `call'
app/api/v1/users.rb:4:in `block in <class:Users>'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 10:58:46 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:16:26 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:16:52 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:16:52 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:16:53 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:17:13 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:17:14 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:00 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:01 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:01 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:01 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:02 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:02 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:18:02 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:19:04 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:19:31 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:19:32 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:19:32 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:21:21 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:08 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:09 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:09 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:09 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:10 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:10 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:10 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:27 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:27 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:27 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:28 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:28 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:28 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-08 11:22:43 +0000
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-10 04:29:15 +0000
  
PG::ConnectionBad (could not translate host name "db" to address: Name does not resolve
):
  
pg (1.2.3) lib/pg.rb:58:in `initialize'
pg (1.2.3) lib/pg.rb:58:in `new'
pg (1.2.3) lib/pg.rb:58:in `connect'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-10 04:29:19 +0000
  
PG::ConnectionBad (could not translate host name "db" to address: Name does not resolve
):
  
pg (1.2.3) lib/pg.rb:58:in `initialize'
pg (1.2.3) lib/pg.rb:58:in `new'
pg (1.2.3) lib/pg.rb:58:in `connect'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:46:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 172.31.0.1 at 2020-08-10 04:34:52 +0000
Started GET "/favicon.ico" for 172.31.0.1 at 2020-08-10 04:34:52 +0000
  
ActionController::RoutingError (No route matches [GET] "/favicon.ico"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:42:58 +0000
  
ActiveRecord::NoDatabaseError (FATAL:  database "savvy-api-rails_development" does not exist
):
  
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:50:in `rescue in postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/postgresql_adapter.rb:33:in `postgresql_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:887:in `new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:931:in `checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:910:in `try_to_checkout_new_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:871:in `acquire_connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:593:in `checkout'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:437:in `connection'
activerecord (6.0.3.2) lib/active_record/connection_adapters/abstract/connection_pool.rb:1119:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:221:in `retrieve_connection'
activerecord (6.0.3.2) lib/active_record/connection_handling.rb:189:in `connection'
activerecord (6.0.3.2) lib/active_record/migration.rb:562:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
  [1m[35m (107.9ms)[0m  [1m[35mCREATE DATABASE "savvy-api-rails_development" ENCODING = 'utf8'[0m
  [1m[35m (92.6ms)[0m  [1m[35mCREATE DATABASE "savvy-api-rails_test" ENCODING = 'utf8'[0m
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:44:01 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:44:42 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1/users"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1" for 172.23.0.1 at 2020-08-13 10:45:51 +0000
  
ActionController::RoutingError (No route matches [GET] "/api/v1"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:46:56 +0000
  
NoMethodError (undefined method `authenticate' for nil:NilClass):
  
app/lib/grape_logging_client_env.rb:6:in `parameters'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:47:17 +0000
  
NoMethodError (undefined method `authenticate' for nil:NilClass):
  
app/lib/grape_logging_client_env.rb:6:in `parameters'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:47:36 +0000
  
NameError (uninitialized constant ApiBase::API
Did you mean?  App):
  
app/api/api_base.rb:31:in `block in <class:ApiBase>'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:47:49 +0000
  
NameError (uninitialized constant ApiBase::API
Did you mean?  App):
  
app/api/api_base.rb:31:in `block in <class:ApiBase>'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:48:57 +0000
Grape::Exceptions::ValidationErrors
  
NameError (uninitialized constant ApiBase::CODE_VALIDATE_FAILED):
  
app/api/api_base.rb:45:in `block in <class:ApiBase>'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:49:43 +0000
Grape::Exceptions::ValidationErrors
  
NameError (uninitialized constant JsonFormatter::Error::API
Did you mean?  App):
  
app/api/json_formatter.rb:46:in `call'
app/api/api_base.rb:49:in `block in <class:ApiBase>'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:49:56 +0000
Grape::Exceptions::ValidationErrors
  
NameError (uninitialized constant JsonFormatter::Error::API
Did you mean?  App):
  
app/api/json_formatter.rb:46:in `call'
app/api/api_base.rb:49:in `block in <class:ApiBase>'
Started GET "/api/v1/users" for 172.23.0.1 at 2020-08-13 10:50:31 +0000
Grape::Exceptions::ValidationErrors
{"response":{"code":"validate_failed","message":["username is missing"],"errors":[{"field":"username","message":"is missing"}]}}
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:53:14 +0000
  
NameError (uninitialized constant JsonFormatter::Success::CODE_SUCCESS
Did you mean?  JsonFormatter::CODE_SUCCESS):
  
app/api/json_formatter.rb:6:in `call'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:54:50 +0000
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:56:40 +0000
  
NameError (uninitialized constant ApplicationService::API):
  
app/services/application_service.rb:3:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:57:11 +0000
  
NameError (uninitialized constant API
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:57:32 +0000
  
NameError (uninitialized constant Api
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:57:51 +0000
  
NameError (uninitialized constant ApplicationService::Api):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:58:10 +0000
  
NameError (uninitialized constant API
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:58:31 +0000
  
NameError (uninitialized constant Api
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:58:44 +0000
  
NameError (uninitialized constant App::API):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.23.0.1 at 2020-08-13 10:58:51 +0000
  
NameError (uninitialized constant App::Api):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.28.0.1 at 2020-08-13 11:15:41 +0000
  
NameError (uninitialized constant API
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.28.0.1 at 2020-08-13 11:16:11 +0000
  
NameError (uninitialized constant API
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:19:01 +0000
  
NameError (uninitialized constant API
Did you mean?  App):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:19:14 +0000
  
NameError (uninitialized constant ApplicationService::API):
  
app/services/application_service.rb:2:in `<class:ApplicationService>'
app/services/application_service.rb:1:in `<main>'
app/services/user_service/get_info.rb:1:in `<main>'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:19:29 +0000
  
NoMethodError (undefined method `call' for UserService::GetInfo:Class):
  
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:20:08 +0000
  
NameError (undefined local variable or method `args' for #<UserService::GetInfo:0x00005562ee183e80>):
  
app/services/user_service/get_info.rb:4:in `call'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:20:45 +0000
  
NoMethodError (undefined method `error!' for #<UserService::GetInfo:0x00005562edff0a78>
Did you mean?  error):
  
app/services/application_service.rb:13:in `error_validate_failed!'
app/services/user_service/get_info.rb:4:in `call'
app/api/v1/users.rb:9:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:20:57 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params dc"}}
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:25:47 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params dc"}}
  [1m[35m (13.6ms)[0m  [1m[35mCREATE TABLE "schema_migrations" ("version" character varying NOT NULL PRIMARY KEY)[0m
  [1m[35m (4.0ms)[0m  [1m[35mCREATE TABLE "ar_internal_metadata" ("key" character varying NOT NULL PRIMARY KEY, "value" character varying, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (0.7ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to CreateUsers (20200813113438)
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (5.2ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[36mprimary::SchemaMigration Create (0.6ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20200813113438"]]
  [1m[35m (1.0ms)[0m  [1m[35mCOMMIT[0m
Migrating to AddColumnInUser (20200813113454)
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (3.2ms)[0m  [1m[35mALTER TABLE "users" ADD "email" character varying NOT NULL[0m
  [1m[35m (0.8ms)[0m  [1m[35mALTER TABLE "users" ADD "token" character varying NOT NULL[0m
  [1m[35m (0.5ms)[0m  [1m[35mALTER TABLE "users" ADD "token_type" character varying[0m
  [1m[36mprimary::SchemaMigration Create (0.4ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20200813113454"]]
  [1m[35m (0.7ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (0.4ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[36mActiveRecord::InternalMetadata Create (1.1ms)[0m  [1m[32mINSERT INTO "ar_internal_metadata" ("key", "value", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "key"[0m  [["key", "environment"], ["value", "development"], ["created_at", "2020-08-13 11:36:08.756258"], ["updated_at", "2020-08-13 11:36:08.756258"]]
  [1m[35m (0.8ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.4ms)[0m  [1m[35mBEGIN[0m
  [1m[36mUser Create (1.7ms)[0m  [1m[32mINSERT INTO "users" ("created_at", "updated_at", "email") VALUES ($1, $2, $3) RETURNING "id"[0m  [["created_at", "2020-08-13 11:36:47.845016"], ["updated_at", "2020-08-13 11:36:47.845016"], ["email", "omliler_man@hotmail.com"]]
  [1m[35m (0.4ms)[0m  [1m[31mROLLBACK[0m
  [1m[35m (0.7ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.3ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to AddColumnInUser (20200813113454)
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (1.1ms)[0m  [1m[35mALTER TABLE "users" DROP COLUMN "email"[0m
  [1m[35m (0.5ms)[0m  [1m[35mALTER TABLE "users" DROP COLUMN "token"[0m
  [1m[35m (0.6ms)[0m  [1m[35mALTER TABLE "users" DROP COLUMN "token_type"[0m
  [1m[36mprimary::SchemaMigration Destroy (0.6ms)[0m  [1m[31mDELETE FROM "schema_migrations" WHERE "schema_migrations"."version" = $1[0m  [["version", "20200813113454"]]
  [1m[35m (0.7ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to AddColumnInUser (20200813113454)
  [1m[35m (0.4ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (0.6ms)[0m  [1m[35mALTER TABLE "users" ADD "email" character varying NOT NULL[0m
  [1m[35m (0.7ms)[0m  [1m[35mALTER TABLE "users" ADD "token" character varying[0m
  [1m[35m (0.6ms)[0m  [1m[35mALTER TABLE "users" ADD "token_type" character varying[0m
  [1m[36mprimary::SchemaMigration Create (0.4ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20200813113454"]]
  [1m[35m (1.2ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (0.4ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.6ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.4ms)[0m  [1m[35mBEGIN[0m
  [1m[36mUser Create (0.9ms)[0m  [1m[32mINSERT INTO "users" ("created_at", "updated_at", "email") VALUES ($1, $2, $3) RETURNING "id"[0m  [["created_at", "2020-08-13 11:37:47.118321"], ["updated_at", "2020-08-13 11:37:47.118321"], ["email", "omliler_man@hotmail.com"]]
  [1m[35m (1.2ms)[0m  [1m[35mCOMMIT[0m
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:39:17 +0000
  [1m[35m (0.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
NameError (undefined local variable or method `user_id' for #<User::GuardValidation:0x00005562eeaee1a0>
Did you mean?  user):
  
app/services/user/guard_validation.rb:4:in `get_info'
app/api/v1/users.rb:6:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users?username=1" for 172.30.0.1 at 2020-08-13 11:39:38 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params user_id"}}
Started GET "/api/v1/users?user_id=1" for 172.30.0.1 at 2020-08-13 11:39:46 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params user_id"}}
Started GET "/api/v1/users?user_id=1" for 172.30.0.1 at 2020-08-13 11:40:21 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params user_id"}}
Started GET "/api/v1/users?user_id=1" for 172.30.0.1 at 2020-08-13 11:41:16 +0000
  [1m[36mUser Load (1.2ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"validate_failed","message":"ไม่มี User นี้จาก user_id: 1"}}
Started GET "/api/v1/users" for 172.30.0.1 at 2020-08-13 11:41:28 +0000
Grape::Exceptions::ValidationErrors
{"response":{"code":"validate_failed","message":["user_id is missing"],"errors":[{"field":"user_id","message":"is missing"}]}}
Started GET "/api/v1/users/2" for 172.30.0.1 at 2020-08-13 11:42:46 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params user_id"}}
Started GET "/api/v1/users/2" for 172.30.0.1 at 2020-08-13 11:43:07 +0000
{"response":{"code":"validate_failed","message":"ไม่มี params user_id"}}
Started GET "/api/v1/users/2" for 172.30.0.1 at 2020-08-13 11:43:42 +0000
  [1m[36mUser Load (0.7ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
  [1m[36mCACHE User Load (0.1ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/get_info.rb:4:in `call'
  
NameError (uninitialized constant V1::Entities::UserEntity):
  
app/api/v1/users.rb:20:in `block (3 levels) in <class:Users>'
Started GET "/api/v1/users/2" for 172.30.0.1 at 2020-08-13 11:43:52 +0000
  [1m[36mUser Load (0.7ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/get_info.rb:4:in `call'
  
NameError (uninitialized constant V1::Entities::User
Did you mean?  V1::Users
               V1::Entities::Users):
  
app/api/v1/users.rb:20:in `block (3 levels) in <class:Users>'
Started GET "/api/v1/users/2" for 172.30.0.1 at 2020-08-13 11:44:20 +0000
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/get_info.rb:4:in `call'
  
NameError (uninitialized constant V1::Entities::User
Did you mean?  V1::Users
               V1::Entities::Users):
  
app/api/v1/users.rb:20:in `block (3 levels) in <class:Users>'
Started GET "/api/v1/users/2" for 172.30.0.1 at 2020-08-13 11:44:41 +0000
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/get_info.rb:4:in `call'
Started GET "/api/v1/users/" for 172.30.0.1 at 2020-08-13 11:44:52 +0000
Grape::Exceptions::ValidationErrors
{"response":{"code":"validate_failed","message":["user_id is missing"],"errors":[{"field":"user_id","message":"is missing"}]}}
Started GET "/api/v1/users/3" for 172.30.0.1 at 2020-08-13 11:45:07 +0000
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 3], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"validate_failed","message":"ไม่มี User นี้จาก user_id: 3"}}
Started GET "/api/v1/users?user_id=1" for 172.30.0.1 at 2020-08-13 11:46:50 +0000
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"validate_failed","message":"ไม่มี User นี้จาก user_id: 1"}}
Started GET "/api/v1/users?user_id=2" for 172.30.0.1 at 2020-08-13 11:46:53 +0000
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
  [1m[36mCACHE User Load (0.0ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  ↳ app/services/user/get_info.rb:4:in `call'
Started GET "/api/v1/users?user_id=3" for 172.30.0.1 at 2020-08-13 11:46:56 +0000
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 3], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"validate_failed","message":"ไม่มี User นี้จาก user_id: 3"}}
Started GET "/api/v1/users" for 172.30.0.1 at 2020-08-13 11:47:00 +0000
Grape::Exceptions::ValidationErrors
{"response":{"code":"validate_failed","message":["user_id is missing"],"errors":[{"field":"user_id","message":"is missing"}]}}
Started GET "/api/v1/users/3" for 172.30.0.1 at 2020-08-13 11:54:53 +0000
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 3], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"validate_failed","message":"ไม่มี User นี้จาก user_id: 3"}}
Started GET "/api/v1/users/3" for 172.30.0.1 at 2020-08-13 11:55:23 +0000
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 3], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"unauthorized","message":"ไม่มี User นี้จาก user_id: 3"}}
Started GET "/api/v1/users/3" for 172.30.0.1 at 2020-08-13 11:56:39 +0000
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 3], ["LIMIT", 1]]
  ↳ app/services/user/guard_validation.rb:5:in `get_info'
{"response":{"code":"validate_failed","message":"ไม่มี User นี้จาก user_id: 3"}}
Started GET "/api/v1/users" for 192.168.16.1 at 2020-08-14 04:46:47 +0000
  [1m[35m (1.6ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
OmniAuth::NoSessionError (You must provide a session to use OmniAuth.):
  
omniauth (1.9.1) lib/omniauth/strategy.rb:180:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users?user_id=3" for 192.168.16.1 at 2020-08-14 04:47:10 +0000
  
OmniAuth::NoSessionError (You must provide a session to use OmniAuth.):
  
omniauth (1.9.1) lib/omniauth/strategy.rb:180:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users?user_id=3" for 192.168.16.1 at 2020-08-14 04:47:19 +0000
  
OmniAuth::NoSessionError (You must provide a session to use OmniAuth.):
  
omniauth (1.9.1) lib/omniauth/strategy.rb:180:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 192.168.16.1 at 2020-08-14 04:48:37 +0000
  
OmniAuth::NoSessionError (You must provide a session to use OmniAuth.):
  
omniauth (1.9.1) lib/omniauth/strategy.rb:180:in `call!'
omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:27:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/users" for 192.168.32.1 at 2020-08-14 04:56:37 +0000
  [1m[35m (0.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
NameError (uninitialized constant #<Class:0x00005598611eff38>::GetInfo
Did you mean?  TZInfo):
  
app/api/v1/users.rb:7:in `block (2 levels) in <class:Users>'
Started GET "/api/v1/users" for 192.168.32.1 at 2020-08-14 04:57:14 +0000
  
NameError (uninitialized constant #<Class:0x0000559861ddebc8>::GetInfo
Did you mean?  TZInfo):
  
app/api/v1/users.rb:7:in `block (2 levels) in <class:Users>'
  [1m[35m (2.0ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (1.0ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to CreateRetirements (20200814102432)
  [1m[35m (0.6ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.4ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (1.2ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to CreateRetirements (20200814102432)
  [1m[35m (0.5ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (53.9ms)[0m  [1m[35mCREATE TABLE "retirements" ("id" bigserial primary key, "user_id" integer NOT NULL, "goal" json, "salary" json, "provident_fund" json, "social_security" json, "saving" json, "post_retirement" json, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[36mprimary::SchemaMigration Create (1.7ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20200814102432"]]
  [1m[35m (3.0ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (1.9ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.5ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[36mUser Load (3.6ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.2ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.3ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mUser Load (0.9ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mUser Load (0.7ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[36mUser Load (0.4ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" ASC LIMIT $1[0m  [["LIMIT", 1]]
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 2], ["LIMIT", 1]]
  [1m[35m (4.2ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (0.6ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to CreateRetirements (20200814102432)
  [1m[35m (1.1ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (14.8ms)[0m  [1m[35mDROP TABLE "retirements"[0m
  [1m[36mprimary::SchemaMigration Destroy (1.3ms)[0m  [1m[31mDELETE FROM "schema_migrations" WHERE "schema_migrations"."version" = $1[0m  [["version", "20200814102432"]]
  [1m[35m (3.6ms)[0m  [1m[35mCOMMIT[0m
Migrating to AddColumnInUser (20200813113454)
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (2.0ms)[0m  [1m[35mALTER TABLE "users" DROP COLUMN "email"[0m
  [1m[35m (1.1ms)[0m  [1m[35mALTER TABLE "users" DROP COLUMN "token"[0m
  [1m[35m (0.8ms)[0m  [1m[35mALTER TABLE "users" DROP COLUMN "token_type"[0m
  [1m[36mprimary::SchemaMigration Destroy (0.7ms)[0m  [1m[31mDELETE FROM "schema_migrations" WHERE "schema_migrations"."version" = $1[0m  [["version", "20200813113454"]]
  [1m[35m (1.2ms)[0m  [1m[35mCOMMIT[0m
Migrating to CreateUsers (20200813113438)
  [1m[35m (0.7ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (1.4ms)[0m  [1m[35mDROP TABLE "users"[0m
  [1m[36mprimary::SchemaMigration Destroy (0.8ms)[0m  [1m[31mDELETE FROM "schema_migrations" WHERE "schema_migrations"."version" = $1[0m  [["version", "20200813113438"]]
  [1m[35m (2.3ms)[0m  [1m[35mCOMMIT[0m
  [1m[35m (0.6ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  [1m[35m (0.5ms)[0m  [1m[34mSELECT pg_try_advisory_lock(8363763324075825855)[0m
  [1m[35m (0.8ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Migrating to CreateUsers (20200813113438)
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  [1m[35m (25.9ms)[0m  [1m[35mCREATE TABLE "users" ("id" bigserial primary key, "email" character varying, "token" character varying, "token_type" character varying, "account_id" character varying, "goal" json, "salary" json, "provident_fund" json, "social_security" json, "saving" json, "post_retirement" json, "created_at" timestamp(6) NOT NULL, "updated_at" timestamp(6) NOT NULL)[0m
  [1m[36mprimary::SchemaMigration Create (0.7ms)[0m  [1m[32mINSERT INTO "schema_migrations" ("version") VALUES ($1) RETURNING "version"[0m  [["version", "20200813113438"]]
  [1m[35m (1.4ms)[0m  [1m[35mCOMMIT[0m
  [1m[36mActiveRecord::InternalMetadata Load (2.7ms)[0m  [1m[34mSELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2[0m  [["key", "environment"], ["LIMIT", 1]]
  [1m[35m (0.8ms)[0m  [1m[34mSELECT pg_advisory_unlock(8363763324075825855)[0m
  [1m[35m (0.9ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
Started GET "/api/v1/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.19.0.1 at 2020-08-25 09:52:59 +0000
  [1m[35m (3.5ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
ActionController::RoutingError (No route matches [GET] "/api/v1/facebook"):
  
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:36:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (6.0.3.2) lib/rails/rack/logger.rb:37:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
activesupport (6.0.3.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.19.0.1 at 2020-08-25 09:53:18 +0000
  
NameError (uninitialized constant V1::Auth::Facebook):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.20.0.1 at 2020-08-25 09:56:06 +0000
  [1m[35m (1.3ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
NameError (uninitialized constant V1::Auth::Facebook):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.20.0.1 at 2020-08-25 09:56:20 +0000
  
Zeitwerk::NameError (expected file /app/app/services/auth/facebook.rb to define constant Auth::Facebook, but didn't):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.20.0.1 at 2020-08-25 09:56:51 +0000
  
NameError (uninitialized constant V1::Auth::Facebook):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.20.0.1 at 2020-08-25 09:57:10 +0000
  
NameError (uninitialized constant V1::Auth::Facebook):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.20.0.1 at 2020-08-25 09:57:27 +0000
  
NameError (uninitialized constant V1::Auth::Facebook):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 09:57:49 +0000
  [1m[35m (1.2ms)[0m  [1m[34mSELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC[0m
  
NameError (uninitialized constant V1::Auth::Facebook):
  
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 09:58:02 +0000
  
NameError (uninitialized constant Auth::Facebook::GuardValidation
Did you mean?  Auth::GuardValidation):
  
app/services/auth/facebook.rb:6:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 09:58:32 +0000
  
NameError (undefined local variable or method `user_id' for #<Auth::Facebook:0x00005648873533f8>):
  
app/services/auth/facebook.rb:6:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 09:58:56 +0000
  
NameError (undefined local variable or method `access_token' for #<Auth::GuardValidation:0x00005648894f1d98>):
  
app/services/auth/guard_validation.rb:5:in `validate_facebook'
app/services/auth/facebook.rb:6:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 09:59:11 +0000
  
NameError (uninitialized constant Auth::Facebook::Request
Did you mean?  Auth::Request):
  
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 09:59:30 +0000
  
NoMethodError (undefined method `request_uri' for #<String:0x000056488a5735e0>):
  
app/services/auth/request.rb:4:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:00:12 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x0000564889998e50>
Did you mean?  gem):
  
app/services/auth/request.rb:6:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:01:31 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x000056488a558308>
Did you mean?  gem):
  
app/services/auth/request.rb:7:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:04:09 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x0000564889572650>
Did you mean?  gem):
  
app/services/auth/request.rb:8:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:05:12 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x000056488a3e02c8>
Did you mean?  gem):
  
app/services/auth/request.rb:9:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:05:54 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x0000564886890448>
Did you mean?  gem):
  
app/services/auth/request.rb:9:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:06:46 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x000056488a248370>
Did you mean?  gem):
  
app/services/auth/request.rb:8:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:07:08 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x0000564886c3c268>
Did you mean?  gem):
  
app/services/auth/request.rb:9:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:07:22 +0000
  
NoMethodError (undefined method `get' for #<URI::HTTPS:0x0000564889f28500>
Did you mean?  gem):
  
app/services/auth/request.rb:12:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:08:07 +0000
  
EOFError (end of file reached):
  
app/services/auth/request.rb:15:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:08:47 +0000
  
EOFError (end of file reached):
  
app/services/auth/request.rb:11:in `call'
app/services/auth/facebook.rb:11:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:10:02 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:10:17 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:11:14 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:11:36 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:13:00 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:13:36 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:14:54 +0000
  
NoMethodError (undefined method `to_hash' for #<String:0x00005648881ccd80>
Did you mean?  to_s):
  
app/services/auth/facebook.rb:13:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:15:02 +0000
  
NoMethodError (undefined method `to_h' for #<String:0x000056488a40a3c0>
Did you mean?  to_d
               to_r
               to_f
               to_c
               to_s
               to_i):
  
app/services/auth/facebook.rb:13:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:15:37 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:16:43 +0000
  
NoMethodError (undefined method `[]' for nil:NilClass):
  
app/services/auth/facebook.rb:15:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:16:54 +0000
  
NoMethodError (undefined method `data' for #<Hash:0x000056488a20f6d8>):
  
app/services/auth/facebook.rb:14:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:17:45 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:19:10 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:19:59 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:20:18 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:20:31 +0000
Started GET "/api/v1/auth/facebook?auth_token=1" for 172.21.0.1 at 2020-08-25 10:20:50 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:21:06 +0000
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:29:26 +0000
  
NoMethodError (undefined method `get_user' for #<Auth::GuardValidation:0x0000564887faf660>):
  
app/services/auth/get_user.rb:4:in `call'
app/services/auth/facebook.rb:16:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:29:42 +0000
  [1m[36mUser Load (2.0ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."token" = $2 AND "users"."token_type" = $3 LIMIT $4[0m  [["account_id", "3386394381382928"], ["token", "EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD"], ["token_type", "facebook"], ["LIMIT", 1]]
  ↳ app/services/auth/get_user.rb:5:in `call'
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" IS NULL LIMIT $1[0m  [["LIMIT", 1]]
  ↳ app/services/auth/guard_validation.rb:23:in `validate_encode'
{"response":{"code":"validate_failed","message":"ไม่มี user id:  นี้อยู่ในระบบ"}}
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:30:05 +0000
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."token" = $2 AND "users"."token_type" = $3 LIMIT $4[0m  [["account_id", "3386394381382928"], ["token", "EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD"], ["token_type", "facebook"], ["LIMIT", 1]]
  ↳ app/services/auth/get_user.rb:5:in `call'
  [1m[35m (0.6ms)[0m  [1m[35mBEGIN[0m
  ↳ app/services/auth/get_user.rb:5:in `call'
  [1m[36mUser Create (3.9ms)[0m  [1m[32mINSERT INTO "users" ("token", "token_type", "account_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"[0m  [["token", "EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD"], ["token_type", "facebook"], ["account_id", "3386394381382928"], ["created_at", "2020-08-25 10:30:06.852861"], ["updated_at", "2020-08-25 10:30:06.852861"]]
  ↳ app/services/auth/get_user.rb:5:in `call'
  [1m[35m (1.6ms)[0m  [1m[35mCOMMIT[0m
  ↳ app/services/auth/get_user.rb:5:in `call'
  
NoMethodError (undefined method `id' for true:TrueClass):
  
app/services/auth/guard_validation.rb:23:in `validate_encode'
app/services/auth/jwt_encode.rb:4:in `call'
app/services/auth/facebook.rb:19:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" ORDER BY "users"."id" DESC LIMIT $1[0m  [["LIMIT", 1]]
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:31:39 +0000
  [1m[36mUser Load (1.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."token" = $2 AND "users"."token_type" = $3 LIMIT $4[0m  [["account_id", "3386394381382928"], ["token", "EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD"], ["token_type", "facebook"], ["LIMIT", 1]]
  ↳ app/services/auth/get_user.rb:5:in `call'
  
NoMethodError (undefined method `id' for true:TrueClass):
  
app/services/auth/guard_validation.rb:23:in `validate_encode'
app/services/auth/jwt_encode.rb:4:in `call'
app/services/auth/facebook.rb:19:in `call'
app/api/v1/auth.rb:11:in `block (2 levels) in <class:Auth>'
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:32:30 +0000
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."token" = $2 AND "users"."token_type" = $3 LIMIT $4[0m  [["account_id", "3386394381382928"], ["token", "EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD"], ["token_type", "facebook"], ["LIMIT", 1]]
  ↳ app/services/auth/get_user.rb:6:in `call'
  [1m[36mUser Load (0.5ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  ↳ app/services/auth/guard_validation.rb:23:in `validate_encode'
  [1m[35m (3.7ms)[0m  [1m[34mSELECT COUNT(*) FROM "users"[0m
Started GET "/api/v1/auth/facebook?auth_token=EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD" for 172.21.0.1 at 2020-08-25 10:34:21 +0000
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."account_id" = $1 AND "users"."token" = $2 AND "users"."token_type" = $3 LIMIT $4[0m  [["account_id", "3386394381382928"], ["token", "EAALJzZCnzhj4BAGLBPrEJV2SruV5ZBau36HpZBTJ1KzPXcaZCxdzl0NHMKCz4K8xTzTdMvpagpihK8rWpnZApFDuL9ZBJLDLMnV6ZAx2ShPlZARXb90C0vBtDVpI7IQdgfZBQyAZAMdNp8FbTHjujrsskVUNZBfwnZCo65ezRYfL5oIFbQZCDwyE8u26IosKafOkut8Yi6KT0ppnzWaUJwmxQ7AWIhAJeBEyiebGo7d171ZBawKQZDZD"], ["token_type", "facebook"], ["LIMIT", 1]]
  ↳ app/services/auth/get_user.rb:6:in `call'
  [1m[36mUser Load (0.6ms)[0m  [1m[34mSELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2[0m  [["id", 1], ["LIMIT", 1]]
  ↳ app/services/auth/guard_validation.rb:23:in `validate_encode'
